### ISSUE TITLE
All links in vue-tree/docs/demos.md are 404

### ISSUE THREAD

**Issue by iamjko** [grapoza/vue-tree#108]
as title

**Comment by grapoza** [comment]
Hi @iamjko, the docs directory is just the input to pandoc that is used to generate the documentation at build time. The actual docs, with demos, can be found on the project's [github pages](https://grapoza.github.io/vue-tree/).

Coincidentally, I'm about to create and issue for and then commit some improvements to the way the docs are built tonight, though the changes won't be live until the 1.1.0 release. The docs currently point to the current released version of the component, no matter which version of the docs you're looking at. After these changes the demos will reference the version of the component that matches the version of the documentation.

I'll also improve the styling on the components for the demos a bit, since right now it's about as basic as it gets; the demos are more about the usage than looks, but they're definitely not pretty. 😄

**Comment by grapoza** [comment]
- [ ] Add README.md to the docs directory that explains its purpose and links to the actual docs pages
- [ ] Ignore the new README.md in generateDocs.ps1

**Comment by iamjko** [comment]
Thx for the infos
