### ISSUE TITLE
input checkbox vs selected Node - not connected

### ISSUE THREAD

**Issue by WpSlt** [grapoza/vue-tree#239]
Goog Work!
I can't figure out how connect node checkbox with note selection,
When flag node checkbox
this.$refs.treeSelection.getSelected() not register action
When click on node label
this.$refs.treeSelection.getSelected() register action but inut checkbox remain unchecked

Some Idea?
Thx a lot!

my code:

				<tree-view
						id="my-tree"
						:load-nodes-async="loadCategoriesAsync"
						:load-children-async="loadChildrenCatAsync"
						:model-defaults="modelDefaults"
						:selection-mode="normalizedSelectionMode"
						ref="treeSelection"
						@tree-view-node-checkbox-change="changeCheckBoxCat"
				></tree-view>

<link href="https://unpkg.com/@grapoza/vue-tree@4.0.2/vue-tree.css" type="text/css" rel="stylesheet">
<script src="https://unpkg.com/@grapoza/vue-tree@4.0.2/vue-tree.umd.min.js"></script>

	const productsApp = Vue.createApp({
        data: function () {
            return {
				TreeData: [
					{id: "numberOrString", label: "Root Node",
					 children: [
					  {id: 1, label: "Child Node"},
					  {id: "node2", label: "Second Child"}]
					}
				  ],
				  modelDefaults: {
					//loadChildrenAsync: this.loadChildrenCatAsync,
					selectable: true,
					expanderTitle: 'Expand this node',
					input: {
						type: 'checkbox',
						disabled: true
					},
					state: {
						expanded: true
					}
				  },
				  selectionMode: 'multiple',
				  selectedNodes: []
			}
		},
        computed: {
			normalizedSelectionMode() {
				return this.selectionMode === '' ? null : this.selectionMode;
			}
		},
        methods: {
			changeCheckBoxCat: function (target, event) {
				console.log('changeCheckBoxCat', target)
				console.log('changeCheckBoxCat', event)
				console.log(this.$refs.treeSelection.getSelected())
                                console.log(this.selectedNodes: undefined)
			},
                    ............
                 }
	});

**Comment by grapoza** [comment]
Ah, I see the confusion. These are actually two separate concerns. Selection deals with the selection of tree nodes themselves, while Checked deals with the state of checkboxes. In the image below, `My First Node` is _checked_, and `This is a subnode` is _selected_. If you want the checked nodes, you can use the `getCheckedCheckboxes()` method instead of `getSelected()` in the code you provided. Hope this helps!

![image](https://user-images.githubusercontent.com/15658149/154528268-c40f7a49-ee0e-40a9-9bb1-81e2bfd2f2e8.png)
