### ISSUE TITLE
Cancel a node deletion

### ISSUE THREAD

**Issue by biscuit314** [grapoza/vue-tree#304]
I'm using grapoza/vue-tree v5.1.0

Is there a way to cancel a deletion, for example:
* to provide an "Are you sure?" prompt
* to cancel deletion if the attempt to sync with a database or API fails

I've added a handler for `treeNodeDelete` and tried returning `false`, throwing an exception, but the delete always completes.  

I also tried setting `treeNodeSpec.deletable` to `false` in the handler.

**Comment by grapoza** [comment]
There's no built-in way to prompt (as you noticed, the `treeNodeDelete` is called after the delete) though an enhancement to add some kind of `treeNodeBeforeDelete` certainly isn't out of the question. I think you have a good use case for that, so if you're interested then feel free to add an enhancement request. Otherwise, I'm having a hard time thinking of a clean way to handle pre-deletion processing (which again indicates an enhancement is probably the way to go here).

I'm currently doing a fairly large refactor and adding native filtering for 5.2, so if an enhancement is required for this I imagine it could make it into that release.

**Comment by biscuit314** [comment]
Thanks for the quick reply.

I've created Feature Request #305

**Comment by grapoza** [comment]
I'm closing this one in favor of Feature Request #305.
